# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'step.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1602, 1205)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gameboard = QtWidgets.QLabel(self.centralwidget)
        self.Gameboard.setGeometry(QtCore.QRect(10, 90, 1200, 1100))
        self.Gameboard.setStyleSheet("border-image: url(:/newPrefix/gameboard.jpg) 0 0 0 0 stretch stretch;")
        self.Gameboard.setText("")
        self.Gameboard.setObjectName("Gameboard")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1600, 1200))
        self.label.setStyleSheet("border-image: url(:/newPrefix/background.jpg) 0 0 0 0 stretch stretch;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.GameTitle = QtWidgets.QLabel(self.centralwidget)
        self.GameTitle.setGeometry(QtCore.QRect(290, 10, 500, 60))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.GameTitle.setFont(font)
        self.GameTitle.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.GameTitle.setObjectName("GameTitle")
        self.Show_Ntbk = QtWidgets.QPushButton(self.centralwidget)
        self.Show_Ntbk.setGeometry(QtCore.QRect(1230, 140, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Show_Ntbk.setFont(font)
        self.Show_Ntbk.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Show_Ntbk.setObjectName("Show_Ntbk")
        self.label.raise_()
        self.Gameboard.raise_()
        self.GameTitle.raise_()
        self.Show_Ntbk.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1602, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReady = QtWidgets.QAction(MainWindow)
        self.actionReady.setObjectName("actionReady")
        self.menuMenu.addAction(self.actionReady)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.Show_Ntbk.clicked.connect(self.Show_Ntbk.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GameTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">ClueLess Game</p></body></html>"))
        self.Show_Ntbk.setText(_translate("MainWindow", "Show Notebook"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionReady.setText(_translate("MainWindow", "Ready"))
import gameboard_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
